### PR TITLE
#18 Add option to disable clock icon

### PR DESCRIPTION
**Pull request by wubli**
To consider positioning of clock when icon is missing

### CODE REVIEW

**Review by mtricht — APPROVED** [review]

**Comment by mtricht** [comment]
Thanks!

**Comment by mtricht** [comment]
Hmm, disabling it does nothing for me, it does for you @wubli ?

**Comment by wubli** [comment]
@mtricht 
rival

Rival 710

**Comment by mtricht** [comment]
@wubli thanks, I finally got it working, had to reinstall steelseries engine :\

Will make a release with this soon

**Pull request merged**
